os: linux
dist: bionic
language: generic
cache:
  directories:
    - $HOME/.stack
addons:
  apt:
    packages:
      - libgmp-dev

before_install:
  # Install z3-4.8
  - wget -O ~/z3-4.8.8-x64-ubuntu-16.04.zip https://github.com/Z3Prover/z3/releases/download/z3-4.8.8/z3-4.8.8-x64-ubuntu-16.04.zip
  - unzip ~/z3-4.8.8-x64-ubuntu-16.04.zip -d ~/
  - export PATH=$HOME/z3-4.8.8-x64-ubuntu-16.04/bin:$PATH

  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  # Build dependencies
  - stack --no-terminal --install-ghc test --only-dependencies

script:
  # Build the package, its tests, and its docs and run the tests
  - stack --no-terminal test --coverage
