name: haskell-sandbox
version: 0.1.0.0
description: |
  Please see the README on GitHub
  at <https://github.com/godu/haskell-sandbox#readme>
author: Arthur Weber
maintainer: arthur.weber@viacesi.fr
license: BSD3
github: godu/haskell-sandbox
extra-source-files:
  - README.md
dependencies:
  - base >= 4.11 && < 5
library:
  source-dirs: src
  dependencies:
    - foldl
    - random
    - semirings
    - syb
    - sbv
    - containers
    - binary
    - bytestring
    - relude
    - text
executables:
  solver:
    main: Main.hs
    source-dirs: app/Solver
    dependencies:
      - haskell-sandbox
      - sbv
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
  cellular:
    main: Main.hs
    source-dirs: app/Cellular
    dependencies:
      - linear
      - gloss
      - random
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
tests:
  haskell-sandbox-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - haskell-sandbox
      - hspec
      - QuickCheck
      - quickcheck-classes
      - random
      - sbv
