name: haskell-sandbox
version: 0.1.0.0
description: |
  Please see the README on GitHub
  at <https://github.com/godu/haskell-sandbox#readme>
author: Arthur Weber
maintainer: arthur.weber@viacesi.fr
license: BSD3
github: godu/haskell-sandbox
extra-source-files:
  - README.md

dependencies:
  - base >= 4.11 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Werror
  - -Wno-name-shadowing
  - -Wno-type-defaults
  - -Wno-missing-signatures
  - -Wno-incomplete-patterns
  - -Wno-unused-matches

library:
  source-dirs: src
  dependencies:
    - random
    - containers

tests:
  haskell-sandbox-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - haskell-sandbox
      - hspec
      - random
      - containers
