name: haskell-sandbox
version: 0.1.0.0
description: |
  Please see the README on GitHub
  at <https://github.com/godu/haskell-sandbox#readme>
author: Arthur Weber
maintainer: arthur.weber@viacesi.fr
license: BSD3
github: godu/haskell-sandbox
extra-source-files:
  - README.md
dependencies:
  - base >= 4.7 && < 5
library:
  source-dirs: src
  dependencies:
    - foldl
    - random
    - semirings
    - sbv
    - syb
executables:
  haskell-sandbox-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-sandbox
      - sbv
tests:
  haskell-sandbox-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-sandbox
      - hspec
      - QuickCheck
      - quickcheck-classes
      - random
      - sbv
